apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-api
  template:
    metadata:
      labels:
        app: my-flask-api
    spec:
      containers:
      - name: my-flask-api-container
        image: elenscode/my-flask-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: HOST_URL
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: host.url
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-api-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: my-flask-api